### ISSUE TITLE
Write "go public" draft

### ISSUE THREAD

**Issue by aaronliunumber2** [Zorbane/foundrymissions#46]
Forum post
Reddit post
Arcgames post?

**Comment by RogueEnterprise** [comment]
I suggest we do the Forum and Reddit post first, and once we get additional traction we can pitch it for potential sponsorship by the official community team.

I'll put something together soon.

**Comment by aaronliunumber2** [comment]
Agree

**Comment by RogueEnterprise** [comment]
Here's a draft, feel free to peruse and edit, etc:

This post is to officially announce the launch of our new website, FoundryMissions.com! You can follow site news on Twitter at @STOmissions.

This site is designed to be a repository and home for Foundry missions for Star Trek Online, and to provide a method to search for them that can provide more than 50 results. The mission listings are curated by the authors themselves!

Foundry Authors:
In contributing your missions to the listings on the site, you have the following features available to you:

•Customize your missions with a number of searchable tags not available via the in-game tagging system
•Upload screenshots, banners and more to your mission postings
•Maintain complete control over your mission description, tags, minimum level, faction and more so your mission is more searchable than ever

Foundry Players:
If you’re looking to play missions, there’s a lot of ways to search the mission listings:

•By gameplay tag to find missions with the content that interests you most
•By author, so you can follow author’s missions across factions
•By minimum level, faction, and more!

We also want your feedback! We have a huge backlog of features we would love to add to the site, but we want to know what you guys, as both authors and players, would like to see as well. Here is just a sampling of what we want to do, and feel free to call them out as things you want, or comment further with features you would want to see!

Future features list:
•Video support/link to YouTube in the media strip for each mission
•Random images on the main page with link to the corresponding mission
•Clicking tags on the mission view screen results in a mission search for that tag
•Twitter integration (Twitter account @STOmissions posts when someone edits or adds a mission)
•Copy mission ID to clipboard function
•Creation of Author homepages, so clicking author names leads to that page instead of search
•Ability to link missions together in a series
•And a lot more!

So please, start using the site and let us know what you think.

**Comment by aaronliunumber2** [comment]
My feedback (all on future features list)

•Change mission tags to clickable boxes on advanced search page
I feel like that's not a new feature but a UI change
from a developer point of view

•HTML/rich
editor for mission descriptions
I don't feel comfortable listing this haha
i think that specifically is going to be a ton of work

Missing feature - Creating a series by putting missions together

**Comment by RogueEnterprise** [comment]
Made those changes to the copy.

**Comment by aaronliunumber2** [comment]
Announcement posts on reddit and forums

**Comment by RogueEnterprise** [comment]
Donesies.
